[package]
name = "chara"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chara"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
